In [17]:
import pandas as pd
import numpy as np

df = pd.DataFrame({'Bull Market': [0.9, 0.075, 0.025], 
                   'Bear Market': [0.15, 0.8, 0.05],
                   'Stagnant Market': [0.25, 0.25, 0.5]}, 
                  index=["Bull Market", "Bear Market", "Stagnant Market"])

def find_trans_prob(df, n):   
    for i in range(2,101):
        if (i == 2 or i == 5 or i == 20 or i == 50 or i == 100):
            print 'The probability after {0} transitions is...\n {1}'.format(i, np.linalg.matrix_power(df, i))
            print "\n"
    return final_state

# How do I determine what the start state is?  Does it matter for this practice problem?

result = find_trans_prob(df, 100)
                
print result

The probability after 2 transitions is...
 [[ 0.755     0.20875   0.3875  ]
 [ 0.1925    0.731875  0.34375 ]
 [ 0.0525    0.059375  0.26875 ]]


The probability after 5 transitions is...
 [[ 0.38472039  0.60421381  0.47521699]
 [ 0.54355691  0.32902491  0.43440576]
 [ 0.0717227   0.06676128  0.09037725]]


The probability after 20 transitions is...
 [[ 0.48902747  0.48679223  0.4879913 ]
 [ 0.44013879  0.44232792  0.44115339]
 [ 0.07083374  0.07087986  0.07085531]]


The probability after 50 transitions is...
 [[ 0.48796802  0.48796779  0.48796792]
 [ 0.44117636  0.44117659  0.44117647]
 [ 0.07085561  0.07085562  0.07085561]]


The probability after 100 transitions is...
 [[ 0.48796791  0.48796791  0.48796791]
 [ 0.44117647  0.44117647  0.44117647]
 [ 0.07085561  0.07085561  0.07085561]]




NameError: global name 'final_state' is not defined